//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KurumsalMVC.Models.Entitiy
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bilgi
    {
        public int BilgiID { get; set; }
        public string tel { get; set; }
        public string eposta { get; set; }
        public string CPR { get; set; }
        public string face { get; set; }
        public string twit { get; set; }
        public string linkedin { get; set; }
        public string skyp { get; set; }
        public string adres { get; set; }
        public string saat { get; set; }
        public string SiteBaslik { get; set; }
        public string SiteAnahtar { get; set; }
        public string SiteAciklama { get; set; }
        public string SİteLogo { get; set; }
    }
}
