//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KurumsalMVC.Models.Entitiy
{
    using System;
    using System.Collections.Generic;
    
    public partial class Blog
    {
        public int BlogID { get; set; }
        public string Baslik { get; set; }
        public string Yazi { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
        public string Resim { get; set; }
        public Nullable<int> Yazar { get; set; }
        public Nullable<int> OkumaSayisi { get; set; }
        public Nullable<int> durum { get; set; }
    
        public virtual Kullanicilar Kullanicilar { get; set; }
    }
}
