//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KurumsalMVC.Models.Entitiy
{
    using System;
    using System.Collections.Generic;
    
    public partial class Projeler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Projeler()
        {
            this.ProjeResimler = new HashSet<ProjeResimler>();
        }
    
        public int ProjeID { get; set; }
        public string Baslik { get; set; }
        public string Yazi { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
        public string Resim { get; set; }
        public Nullable<int> KategoriID { get; set; }
        public Nullable<int> Durum { get; set; }
    
        public virtual ProjeKategoriler ProjeKategoriler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjeResimler> ProjeResimler { get; set; }
    }
}
