//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KurumsalMVC.Models.Entitiy
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjeResimler
    {
        public int ResimID { get; set; }
        public string ResimURL { get; set; }
        public Nullable<int> ProjeID { get; set; }
    
        public virtual Projeler Projeler { get; set; }
    }
}
